### ISSUE TITLE
Seed from joseluis/blessings

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses-rs#1]
This new implementation of the crate comes from `joseluis/blessings`, replacing `dankamongmen/notcurses/rust/notcurses` in the `notcurses` namespace. It will be dual-licensed under ASL2.0/MIT, per https://github.com/dankamongmen/notcurses/issues/874.

I've invited @joseluis to be a coadministrator of the crate, which ought give him sufficient privileges to upload as he deems fit.

Please go ahead and seed this repo, and verify that you can upload `notcurses` to crates.io, using either 1.99 or 2.0 as you see fit.

**Comment by joseluis** [comment]
Good. I'll find the right moment this week to inaugurate it.

**Comment by joseluis** [comment]
Ok done.

But I wont be publishing an updated crate to crates.io yet. Mainly because it only allows to have dependencies fetched from crates.io, and ATM this project depends on the 2 pre-released versions of `libnotcurses-sys` & `enumflags2`. Once both next versions gets published, I'll be free to do the same with this one.
